QT -= gui

CONFIG += c++14 console
CONFIG -= app_bundle

# The following define makes your compiler emit warnings if you use
# any feature of Qt which as been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += main.cpp \
    mainapplication.cpp \
    main.cpp \
    mainapplication.cpp \
    frontpagewidget.cpp \
    ToolKit/wjavascriptslider.cpp \
    contentpage.cpp \
    src/haberlerpage.cpp \
    src/storepage.cpp \
    src/fikturpage.cpp \
    src/footer.cpp \
    src/taraftarpage.cpp

HEADERS += \
    mainapplication.h \
    mainapplication.h \
    frontpagewidget.h \
    ToolKit/wjavascriptslider.h \
    contentpage.h \
    src/haberlerpage.h \
    src/storepage.h \
    ToolKit/bootstrap.h \
    src/fikturpage.h \
    src/footer.h \
    src/taraftarpage.h




win32: LIBS += -L$$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/lib/ -lwt

INCLUDEPATH += $$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/include
DEPENDPATH += $$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/include


win32: LIBS += -L$$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/lib/ -lwthttp

INCLUDEPATH += $$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/include
DEPENDPATH += $$PWD/../../Server/WebServer/Wt-4.0.0-msvs2015-Windows-x64-SDK/include

DISTFILES += \
    docroot/css/mainPage.css \
    docroot/resources/font-awesome/fonts/fontawesome-webfont.woff \
    docroot/resources/jPlayer/jquery.jplayer.js \
    docroot/resources/jPlayer/jquery.jplayer.min.js \
    docroot/resources/jPlayer/jquery.min.js \
    docroot/resources/tiny_mce/langs/en.js \
    docroot/resources/tiny_mce/plugins/advhr/js/rule.js \
    docroot/resources/tiny_mce/plugins/advhr/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/advhr/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/advhr/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/advimage/js/image.js \
    docroot/resources/tiny_mce/plugins/advimage/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/advimage/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/advimage/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/advlink/js/advlink.js \
    docroot/resources/tiny_mce/plugins/advlink/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/advlink/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/advlink/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/advlist/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/advlist/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/autolink/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/autolink/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/autoresize/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/autoresize/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/autosave/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/autosave/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/bbcode/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/bbcode/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/contextmenu/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/contextmenu/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/directionality/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/directionality/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/emotions/js/emotions.js \
    docroot/resources/tiny_mce/plugins/emotions/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/emotions/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/emotions/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/example/js/dialog.js \
    docroot/resources/tiny_mce/plugins/example/langs/en.js \
    docroot/resources/tiny_mce/plugins/example/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/example/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/example/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/example_dependency/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/example_dependency/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/fullpage/js/fullpage.js \
    docroot/resources/tiny_mce/plugins/fullpage/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/fullpage/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/fullpage/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/fullscreen/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/fullscreen/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/iespell/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/iespell/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/inlinepopups/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/inlinepopups/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/insertdatetime/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/insertdatetime/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/layer/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/layer/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/legacyoutput/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/legacyoutput/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/lists/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/lists/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/media/js/embed.js \
    docroot/resources/tiny_mce/plugins/media/js/media.js \
    docroot/resources/tiny_mce/plugins/media/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/media/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/media/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/nonbreaking/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/nonbreaking/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/noneditable/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/noneditable/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/pagebreak/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/pagebreak/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/paste/js/pastetext.js \
    docroot/resources/tiny_mce/plugins/paste/js/pasteword.js \
    docroot/resources/tiny_mce/plugins/paste/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/paste/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/paste/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/preview/jscripts/embed.js \
    docroot/resources/tiny_mce/plugins/preview/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/preview/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/print/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/print/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/save/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/save/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/searchreplace/js/searchreplace.js \
    docroot/resources/tiny_mce/plugins/searchreplace/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/searchreplace/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/searchreplace/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/spellchecker/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/spellchecker/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/style/js/props.js \
    docroot/resources/tiny_mce/plugins/style/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/style/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/style/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/tabfocus/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/tabfocus/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/table/js/cell.js \
    docroot/resources/tiny_mce/plugins/table/js/merge_cells.js \
    docroot/resources/tiny_mce/plugins/table/js/row.js \
    docroot/resources/tiny_mce/plugins/table/js/table.js \
    docroot/resources/tiny_mce/plugins/table/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/table/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/table/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/template/js/template.js \
    docroot/resources/tiny_mce/plugins/template/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/template/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/template/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/visualblocks/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/visualblocks/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/visualchars/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/visualchars/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/wordcount/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/wordcount/editor_plugin_src.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/abbr.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/acronym.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/attributes.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/cite.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/del.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/element_common.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/js/ins.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/langs/en_dlg.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/editor_plugin.js \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/editor_plugin_src.js \
    docroot/resources/tiny_mce/themes/advanced/js/about.js \
    docroot/resources/tiny_mce/themes/advanced/js/anchor.js \
    docroot/resources/tiny_mce/themes/advanced/js/charmap.js \
    docroot/resources/tiny_mce/themes/advanced/js/color_picker.js \
    docroot/resources/tiny_mce/themes/advanced/js/image.js \
    docroot/resources/tiny_mce/themes/advanced/js/link.js \
    docroot/resources/tiny_mce/themes/advanced/js/source_editor.js \
    docroot/resources/tiny_mce/themes/advanced/langs/en.js \
    docroot/resources/tiny_mce/themes/advanced/langs/en_dlg.js \
    docroot/resources/tiny_mce/themes/advanced/editor_template.js \
    docroot/resources/tiny_mce/themes/advanced/editor_template_src.js \
    docroot/resources/tiny_mce/themes/simple/langs/en.js \
    docroot/resources/tiny_mce/themes/simple/editor_template.js \
    docroot/resources/tiny_mce/themes/simple/editor_template_src.js \
    docroot/resources/tiny_mce/utils/editable_selects.js \
    docroot/resources/tiny_mce/utils/form_utils.js \
    docroot/resources/tiny_mce/utils/mctabs.js \
    docroot/resources/tiny_mce/utils/validate.js \
    docroot/resources/tiny_mce/tiny_mce.js \
    docroot/resources/tiny_mce/tiny_mce_popup.js \
    docroot/resources/font-awesome/fonts/fontawesome-webfont.eot \
    docroot/resources/font-awesome/fonts/fontawesome-webfont.woff2 \
    docroot/resources/jPlayer/jquery.jplayer.swf \
    docroot/resources/tiny_mce/plugins/media/moxieplayer.swf \
    docroot/resources/font-awesome/fonts/FontAwesome.otf \
    docroot/resources/font-awesome/fonts/fontawesome-webfont.ttf \
    docroot/resources/themes/bootstrap/stripes/generate.sh \
    docroot/resources/themes/default/no-stripes/generate.sh \
    docroot/resources/themes/default/stripes/generate.sh \
    docroot/resources/themes/polished/no-stripes/generate.sh \
    docroot/resources/themes/polished/stripes/generate.sh \
    approot/wt_config.xml \
    docroot/resources/jPlayer/skin/jplayer.blue.monday.seeking.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-10px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-11px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-12px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-13px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-14px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-15px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-16px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-17px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-18px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-19px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-20px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-21px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-22px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-23px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-24px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-25px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-26px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-27px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-28px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-29px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-30px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-31px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-32px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-33px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-34px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-35px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-36px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-37px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-38px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-39px.gif \
    docroot/resources/themes/bootstrap/stripes/stripe-40px.gif \
    docroot/resources/themes/bootstrap/nav-minus-rtl.gif \
    docroot/resources/themes/bootstrap/nav-minus.gif \
    docroot/resources/themes/bootstrap/nav-plus-rtl.gif \
    docroot/resources/themes/bootstrap/nav-plus.gif \
    docroot/resources/themes/bootstrap/sort-arrow-down.gif \
    docroot/resources/themes/bootstrap/sort-arrow-none.gif \
    docroot/resources/themes/bootstrap/sort-arrow-up.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-10px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-11px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-12px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-13px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-14px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-15px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-16px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-17px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-18px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-19px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-20px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-21px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-22px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-23px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-24px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-25px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-26px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-27px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-28px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-29px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-30px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-31px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-32px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-33px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-34px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-35px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-36px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-37px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-38px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-39px.gif \
    docroot/resources/themes/default/no-stripes/no-stripe-40px.gif \
    docroot/resources/themes/default/stripes/stripe-10px.gif \
    docroot/resources/themes/default/stripes/stripe-11px.gif \
    docroot/resources/themes/default/stripes/stripe-12px.gif \
    docroot/resources/themes/default/stripes/stripe-13px.gif \
    docroot/resources/themes/default/stripes/stripe-14px.gif \
    docroot/resources/themes/default/stripes/stripe-15px.gif \
    docroot/resources/themes/default/stripes/stripe-16px.gif \
    docroot/resources/themes/default/stripes/stripe-17px.gif \
    docroot/resources/themes/default/stripes/stripe-18px.gif \
    docroot/resources/themes/default/stripes/stripe-19px.gif \
    docroot/resources/themes/default/stripes/stripe-20px.gif \
    docroot/resources/themes/default/stripes/stripe-21px.gif \
    docroot/resources/themes/default/stripes/stripe-22px.gif \
    docroot/resources/themes/default/stripes/stripe-23px.gif \
    docroot/resources/themes/default/stripes/stripe-24px.gif \
    docroot/resources/themes/default/stripes/stripe-25px.gif \
    docroot/resources/themes/default/stripes/stripe-26px.gif \
    docroot/resources/themes/default/stripes/stripe-27px.gif \
    docroot/resources/themes/default/stripes/stripe-28px.gif \
    docroot/resources/themes/default/stripes/stripe-29px.gif \
    docroot/resources/themes/default/stripes/stripe-30px.gif \
    docroot/resources/themes/default/stripes/stripe-31px.gif \
    docroot/resources/themes/default/stripes/stripe-32px.gif \
    docroot/resources/themes/default/stripes/stripe-33px.gif \
    docroot/resources/themes/default/stripes/stripe-34px.gif \
    docroot/resources/themes/default/stripes/stripe-35px.gif \
    docroot/resources/themes/default/stripes/stripe-36px.gif \
    docroot/resources/themes/default/stripes/stripe-37px.gif \
    docroot/resources/themes/default/stripes/stripe-38px.gif \
    docroot/resources/themes/default/stripes/stripe-39px.gif \
    docroot/resources/themes/default/stripes/stripe-40px.gif \
    docroot/resources/themes/default/nav-minus-rtl.gif \
    docroot/resources/themes/default/nav-minus.gif \
    docroot/resources/themes/default/nav-plus-rtl.gif \
    docroot/resources/themes/default/nav-plus.gif \
    docroot/resources/themes/default/slider-thumb-h-disabled.gif \
    docroot/resources/themes/default/slider-thumb-h.gif \
    docroot/resources/themes/default/slider-thumb-v-disabled.gif \
    docroot/resources/themes/default/slider-thumb-v.gif \
    docroot/resources/themes/default/sort-arrow-disabled.gif \
    docroot/resources/themes/default/sort-arrow-down.gif \
    docroot/resources/themes/default/sort-arrow-none.gif \
    docroot/resources/themes/default/sort-arrow-up.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-10px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-11px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-12px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-13px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-14px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-15px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-16px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-17px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-18px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-19px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-20px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-21px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-22px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-23px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-24px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-25px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-26px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-27px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-28px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-29px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-30px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-31px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-32px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-33px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-34px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-35px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-36px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-37px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-38px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-39px.gif \
    docroot/resources/themes/polished/no-stripes/no-stripe-40px.gif \
    docroot/resources/themes/polished/stripes/stripe-10px.gif \
    docroot/resources/themes/polished/stripes/stripe-11px.gif \
    docroot/resources/themes/polished/stripes/stripe-12px.gif \
    docroot/resources/themes/polished/stripes/stripe-13px.gif \
    docroot/resources/themes/polished/stripes/stripe-14px.gif \
    docroot/resources/themes/polished/stripes/stripe-15px.gif \
    docroot/resources/themes/polished/stripes/stripe-16px.gif \
    docroot/resources/themes/polished/stripes/stripe-17px.gif \
    docroot/resources/themes/polished/stripes/stripe-18px.gif \
    docroot/resources/themes/polished/stripes/stripe-19px.gif \
    docroot/resources/themes/polished/stripes/stripe-20px.gif \
    docroot/resources/themes/polished/stripes/stripe-21px.gif \
    docroot/resources/themes/polished/stripes/stripe-22px.gif \
    docroot/resources/themes/polished/stripes/stripe-23px.gif \
    docroot/resources/themes/polished/stripes/stripe-24px.gif \
    docroot/resources/themes/polished/stripes/stripe-25px.gif \
    docroot/resources/themes/polished/stripes/stripe-26px.gif \
    docroot/resources/themes/polished/stripes/stripe-27px.gif \
    docroot/resources/themes/polished/stripes/stripe-28px.gif \
    docroot/resources/themes/polished/stripes/stripe-29px.gif \
    docroot/resources/themes/polished/stripes/stripe-30px.gif \
    docroot/resources/themes/polished/stripes/stripe-31px.gif \
    docroot/resources/themes/polished/stripes/stripe-32px.gif \
    docroot/resources/themes/polished/stripes/stripe-33px.gif \
    docroot/resources/themes/polished/stripes/stripe-34px.gif \
    docroot/resources/themes/polished/stripes/stripe-35px.gif \
    docroot/resources/themes/polished/stripes/stripe-36px.gif \
    docroot/resources/themes/polished/stripes/stripe-37px.gif \
    docroot/resources/themes/polished/stripes/stripe-38px.gif \
    docroot/resources/themes/polished/stripes/stripe-39px.gif \
    docroot/resources/themes/polished/stripes/stripe-40px.gif \
    docroot/resources/themes/polished/nav-minus-rtl.gif \
    docroot/resources/themes/polished/nav-minus.gif \
    docroot/resources/themes/polished/nav-plus-rtl.gif \
    docroot/resources/themes/polished/nav-plus.gif \
    docroot/resources/themes/polished/sort-arrow-disabled.gif \
    docroot/resources/themes/polished/sort-arrow-down.gif \
    docroot/resources/themes/polished/sort-arrow-none.gif \
    docroot/resources/themes/polished/sort-arrow-up.gif \
    docroot/resources/tiny_mce/plugins/advimage/img/sample.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-cool.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-cry.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-embarassed.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-foot-in-mouth.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-frown.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-innocent.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-kiss.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-laughing.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-money-mouth.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-sealed.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-smile.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-surprised.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-tongue-out.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-undecided.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-wink.gif \
    docroot/resources/tiny_mce/plugins/emotions/img/smiley-yell.gif \
    docroot/resources/tiny_mce/plugins/example/img/example.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/alert.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/button.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/buttons.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/confirm.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/corners.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/horizontal.gif \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/img/vertical.gif \
    docroot/resources/tiny_mce/plugins/spellchecker/img/wline.gif \
    docroot/resources/tiny_mce/themes/advanced/img/flash.gif \
    docroot/resources/tiny_mce/themes/advanced/img/icons.gif \
    docroot/resources/tiny_mce/themes/advanced/img/iframe.gif \
    docroot/resources/tiny_mce/themes/advanced/img/pagebreak.gif \
    docroot/resources/tiny_mce/themes/advanced/img/quicktime.gif \
    docroot/resources/tiny_mce/themes/advanced/img/realmedia.gif \
    docroot/resources/tiny_mce/themes/advanced/img/shockwave.gif \
    docroot/resources/tiny_mce/themes/advanced/img/trans.gif \
    docroot/resources/tiny_mce/themes/advanced/img/video.gif \
    docroot/resources/tiny_mce/themes/advanced/img/windowsmedia.gif \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/items.gif \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/menu_arrow.gif \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/menu_check.gif \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/progress.gif \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/tabs.gif \
    docroot/resources/tiny_mce/themes/simple/img/icons.gif \
    docroot/resources/ajax-loading.gif \
    docroot/resources/collapse-rtl.gif \
    docroot/resources/collapse.gif \
    docroot/resources/expand-rtl.gif \
    docroot/resources/expand.gif \
    docroot/resources/items-not-ok.gif \
    docroot/resources/items-ok.gif \
    docroot/resources/items.gif \
    docroot/resources/line-last-rtl.gif \
    docroot/resources/line-last.gif \
    docroot/resources/line-middle-rtl.gif \
    docroot/resources/line-middle.gif \
    docroot/resources/line-trunk.gif \
    docroot/resources/minus.gif \
    docroot/resources/plus.gif \
    docroot/resources/right-arrow.gif \
    docroot/resources/tab_b.gif \
    docroot/resources/tab_l.gif \
    docroot/resources/tab_r.gif \
    docroot/resources/tv-line-last-rtl.gif \
    docroot/resources/tv-line-last.gif \
    docroot/resources/jPlayer/skin/jplayer.blue.monday.jpg \
    docroot/resources/tiny_mce/themes/advanced/img/colorpicker.jpg \
    docroot/resources/jPlayer/skin/jplayer.blue.monday.video.play.png \
    docroot/resources/themes/bootstrap/2/date-edit-button.png \
    docroot/resources/themes/bootstrap/2/spin-buttons.png \
    docroot/resources/themes/bootstrap/2/suggest-dropdown.png \
    docroot/resources/themes/bootstrap/2/time-edit-button.png \
    docroot/resources/themes/bootstrap/3/date-edit-button.png \
    docroot/resources/themes/bootstrap/3/spin-buttons.png \
    docroot/resources/themes/bootstrap/3/suggest-dropdown.png \
    docroot/resources/themes/bootstrap/3/time-edit-button.png \
    docroot/resources/themes/bootstrap/img/glyphicons-halflings-white.png \
    docroot/resources/themes/bootstrap/img/glyphicons-halflings.png \
    docroot/resources/themes/bootstrap/splitter-h.png \
    docroot/resources/themes/bootstrap/splitter-v.png \
    docroot/resources/themes/default/closeicons-dialog.png \
    docroot/resources/themes/default/closeicons-mi.png \
    docroot/resources/themes/default/closeicons-tab.png \
    docroot/resources/themes/default/dropdown.png \
    docroot/resources/themes/default/sliderbg-h-disabled.png \
    docroot/resources/themes/default/sliderbg-h.png \
    docroot/resources/themes/default/sliderbg-v-disabled.png \
    docroot/resources/themes/default/sliderbg-v.png \
    docroot/resources/themes/default/spin-buttons-dn.png \
    docroot/resources/themes/default/spin-buttons-up.png \
    docroot/resources/themes/default/spin-buttons.png \
    docroot/resources/themes/default/splitter-h.png \
    docroot/resources/themes/default/splitter-v.png \
    docroot/resources/themes/polished/closeicons-dialog.png \
    docroot/resources/themes/polished/closeicons-mi.png \
    docroot/resources/themes/polished/closeicons-tab.png \
    docroot/resources/themes/polished/dropdown.png \
    docroot/resources/themes/polished/dropshadow.png \
    docroot/resources/themes/polished/gradient.png \
    docroot/resources/themes/polished/nav-minus-rtl.png \
    docroot/resources/themes/polished/nav-minus.png \
    docroot/resources/themes/polished/nav-plus-rtl.png \
    docroot/resources/themes/polished/nav-plus.png \
    docroot/resources/themes/polished/slider-thumb-disabled.png \
    docroot/resources/themes/polished/slider-thumb.png \
    docroot/resources/themes/polished/sliderbg-h-disabled.png \
    docroot/resources/themes/polished/sliderbg-h.png \
    docroot/resources/themes/polished/sliderbg-he-disabled.png \
    docroot/resources/themes/polished/sliderbg-he.png \
    docroot/resources/themes/polished/sliderbg-hw-disabled.png \
    docroot/resources/themes/polished/sliderbg-hw.png \
    docroot/resources/themes/polished/sliderbg-v-disabled.png \
    docroot/resources/themes/polished/sliderbg-v.png \
    docroot/resources/themes/polished/sliderbg-ve-disabled.png \
    docroot/resources/themes/polished/sliderbg-ve.png \
    docroot/resources/themes/polished/sliderbg-vw-disabled.png \
    docroot/resources/themes/polished/sliderbg-vw.png \
    docroot/resources/themes/polished/splitter-h.png \
    docroot/resources/themes/polished/splitter-v.png \
    docroot/resources/themes/polished/suggest-dropdown.png \
    docroot/resources/themes/polished/title-gradient.png \
    docroot/resources/tiny_mce/themes/advanced/skins/default/img/buttons.png \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/img/button_bg.png \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_black.png \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/img/button_bg_silver.png \
    docroot/resources/tiny_mce/themes/simple/skins/o2k7/img/button_bg.png \
    docroot/resources/calendar_edit.png \
    docroot/resources/loading.png \
    docroot/resources/resizable.png \
    docroot/resources/font-awesome/fonts/fontawesome-webfont.svg \
    docroot/resources/themes/bootstrap/2/date-edit-button.svg \
    docroot/resources/themes/bootstrap/2/spin-buttons.svg \
    docroot/resources/themes/bootstrap/2/suggest-dropdown.svg \
    docroot/resources/themes/bootstrap/3/date-edit-button.svg \
    docroot/resources/themes/bootstrap/3/spin-buttons.svg \
    docroot/resources/themes/bootstrap/3/suggest-dropdown.svg \
    docroot/css/mainPage.css \
    docroot/resources/font-awesome/css/font-awesome.css \
    docroot/resources/font-awesome/css/font-awesome.min.css \
    docroot/resources/jPlayer/skin/jplayer.blue.monday.css \
    docroot/resources/themes/bootstrap/2/bootstrap-responsive.css \
    docroot/resources/themes/bootstrap/2/bootstrap-responsive.min.css \
    docroot/resources/themes/bootstrap/2/bootstrap.css \
    docroot/resources/themes/bootstrap/2/bootstrap.min.css \
    docroot/resources/themes/bootstrap/2/wt.css \
    docroot/resources/themes/bootstrap/3/bootstrap-theme.css \
    docroot/resources/themes/bootstrap/3/bootstrap-theme.min.css \
    docroot/resources/themes/bootstrap/3/bootstrap.css \
    docroot/resources/themes/bootstrap/3/bootstrap.min.css \
    docroot/resources/themes/bootstrap/3/wt.css \
    docroot/resources/themes/default/wt.css \
    docroot/resources/themes/default/wt_ie.css \
    docroot/resources/themes/default/wt_ie6.css \
    docroot/resources/themes/polished/wt.css \
    docroot/resources/themes/polished/wt_ie.css \
    docroot/resources/themes/polished/wt_ie6.css \
    docroot/resources/tiny_mce/plugins/advhr/css/advhr.css \
    docroot/resources/tiny_mce/plugins/advimage/css/advimage.css \
    docroot/resources/tiny_mce/plugins/advlink/css/advlink.css \
    docroot/resources/tiny_mce/plugins/fullpage/css/fullpage.css \
    docroot/resources/tiny_mce/plugins/inlinepopups/skins/clearlooks2/window.css \
    docroot/resources/tiny_mce/plugins/media/css/media.css \
    docroot/resources/tiny_mce/plugins/searchreplace/css/searchreplace.css \
    docroot/resources/tiny_mce/plugins/spellchecker/css/content.css \
    docroot/resources/tiny_mce/plugins/style/css/props.css \
    docroot/resources/tiny_mce/plugins/table/css/cell.css \
    docroot/resources/tiny_mce/plugins/table/css/row.css \
    docroot/resources/tiny_mce/plugins/table/css/table.css \
    docroot/resources/tiny_mce/plugins/template/css/template.css \
    docroot/resources/tiny_mce/plugins/visualblocks/css/visualblocks.css \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/css/attributes.css \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/css/popup.css \
    docroot/resources/tiny_mce/themes/advanced/skins/default/content.css \
    docroot/resources/tiny_mce/themes/advanced/skins/default/dialog.css \
    docroot/resources/tiny_mce/themes/advanced/skins/default/ui.css \
    docroot/resources/tiny_mce/themes/advanced/skins/highcontrast/content.css \
    docroot/resources/tiny_mce/themes/advanced/skins/highcontrast/dialog.css \
    docroot/resources/tiny_mce/themes/advanced/skins/highcontrast/ui.css \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/content.css \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/dialog.css \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/ui.css \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/ui_black.css \
    docroot/resources/tiny_mce/themes/advanced/skins/o2k7/ui_silver.css \
    docroot/resources/tiny_mce/themes/simple/skins/default/content.css \
    docroot/resources/tiny_mce/themes/simple/skins/default/ui.css \
    docroot/resources/tiny_mce/themes/simple/skins/o2k7/content.css \
    docroot/resources/tiny_mce/themes/simple/skins/o2k7/ui.css \
    docroot/resources/form.css \
    docroot/resources/html4_default.css \
    docroot/resources/moz-transitions.css \
    docroot/resources/style.css \
    docroot/resources/transitions.css \
    docroot/resources/webkit-transitions.css \
    docroot/resources/tiny_mce/plugins/advhr/rule.htm \
    docroot/resources/tiny_mce/plugins/advimage/image.htm \
    docroot/resources/tiny_mce/plugins/advlink/link.htm \
    docroot/resources/tiny_mce/plugins/emotions/emotions.htm \
    docroot/resources/tiny_mce/plugins/example/dialog.htm \
    docroot/resources/tiny_mce/plugins/fullpage/fullpage.htm \
    docroot/resources/tiny_mce/plugins/fullscreen/fullscreen.htm \
    docroot/resources/tiny_mce/plugins/inlinepopups/template.htm \
    docroot/resources/tiny_mce/plugins/media/media.htm \
    docroot/resources/tiny_mce/plugins/paste/pastetext.htm \
    docroot/resources/tiny_mce/plugins/paste/pasteword.htm \
    docroot/resources/tiny_mce/plugins/preview/example.html \
    docroot/resources/tiny_mce/plugins/preview/preview.html \
    docroot/resources/tiny_mce/plugins/searchreplace/searchreplace.htm \
    docroot/resources/tiny_mce/plugins/style/props.htm \
    docroot/resources/tiny_mce/plugins/table/cell.htm \
    docroot/resources/tiny_mce/plugins/table/merge_cells.htm \
    docroot/resources/tiny_mce/plugins/table/row.htm \
    docroot/resources/tiny_mce/plugins/table/table.htm \
    docroot/resources/tiny_mce/plugins/template/blank.htm \
    docroot/resources/tiny_mce/plugins/template/template.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/abbr.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/acronym.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/attributes.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/cite.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/del.htm \
    docroot/resources/tiny_mce/plugins/xhtmlxtras/ins.htm \
    docroot/resources/tiny_mce/themes/advanced/about.htm \
    docroot/resources/tiny_mce/themes/advanced/anchor.htm \
    docroot/resources/tiny_mce/themes/advanced/charmap.htm \
    docroot/resources/tiny_mce/themes/advanced/color_picker.htm \
    docroot/resources/tiny_mce/themes/advanced/image.htm \
    docroot/resources/tiny_mce/themes/advanced/link.htm \
    docroot/resources/tiny_mce/themes/advanced/shortcuts.htm \
    docroot/resources/tiny_mce/themes/advanced/source_editor.htm \
    docroot/resources/font-awesome/LICENSE.txt \
    docroot/resources/themes/bootstrap/2/wt.less \
    docroot/resources/themes/bootstrap/3/bootstrap-theme.css.map \
    docroot/resources/themes/bootstrap/3/bootstrap-theme.min.css.map \
    docroot/resources/themes/bootstrap/3/bootstrap.css.map \
    docroot/resources/themes/bootstrap/3/bootstrap.min.css.map \
    docroot/resources/themes/bootstrap/3/wt.less \
    docroot/resources/tiny_mce/plugins/style/readme.txt \
    Necessary \
    docroot/img/serikbelediyesporlogo.png \
    docroot/script/script.js \
    docroot/css/test.css
